vidName = 'Pipe.cine';
vr = CineReader(fullfile('../data/MotionMicroscope', vidName));

%%
[motion1, motionCovariance1] =  computeMotionAndCovariance(vr, ...
            'sigma', 6, ...
             'useFrames', [1, 300], 'useMex', true);
%%
[motion2, motionCovariance2] =  computeMotionAndCovariance(vr, ...
            'sigma', 6, ...
             'useFrames', [1, 300], 'useMex', false);